language: node_js
node_js:
  - "12"
  - "10"
deploy:
  on:
    tags: true
    branch: master
  provider: npm
  email: open-source-ops@aexp.com
  api_key:
    secure: NqpJhojWkvDpwZet3KGmg4rAG79Bz/nE/5NOO3QKZ9dQMjqDvWNctroYboT9BLvWzhlLKfXWwtW2a7OgJVe17vXYQy4MP15AD78t/4x/+QCx1TDLwKOKeG5AuVgxwttJ0a0NNPoc2t+ysymYNtkn8HGLuM47nsQ5q1Ngy7nI14TwYlIFPKfro+0rn7zSj7nSnFWw5Xrxpq+mYRVincm3i3s/zHjSpBYBHKZG505EjhmsSntivLrYTqp3trwV6EMXJIhsBaaxnngGShmgzXR78Dc/lnYzl/hJSJYz7WmFrfidwnb3Wte+eGPcgM5OJcJzO1kyH7HL2ghbcijuqGBvy0pXxegefOtHwROOiAbcEI+taqUzAM+fAc9ncs4YVWLqO+8NT6uiVht0bNYV6IciF885FxxgL2JAR07o2v1bNhK9Fz/su+lZzUBYbUeZGnIQXt0BPGv/j1h3AKwwsjYT/YN8gnNsDxmUqtQ9YYDdhuU8evqDCcKdrbq1PP3LLb/s1NvY/D4Bwl+QSXOU6ihVZ56ogzzM6To9NZ8Mpv85T06OJCw55whTfZi6ZhTvfqAlzCvtlXNEX2wF43DG447ctsGoJGRmrOx+fCsMbEFyEuOeRThlly50A50dfyJqizkpDexcx0fSqz0iY/cy4R7uFaXkuH5mQ/iYvSrCICz5L8U=
